---

- name: get current version
  command: /usr/local/bin/redis-cli -v
  register: result
  ignore_errors: True
  changed_when: False

- name: download
  get_url: url={{ download.redis.url }} dest=/tmp/{{ download.redis.url | basename }}
  when: result.rc != 0 or result.stdout.split()[1] != software.redis.version

- name: extract
  unarchive: src=/tmp/{{ download.redis.url | basename }} dest=/tmp copy=no
  when: result.rc != 0 or result.stdout.split()[1] != software.redis.version

- name: compile
  command: make -j{{ ansible_processor_cores }} chdir=/tmp/redis-{{ software.redis.version }}
  when: result.rc != 0 or result.stdout.split()[1] != software.redis.version

- name: create data directory
  file: path=/var/lib/redis state=directory recurse=yes

- name: create logs directory
  file: path=/var/log/redis state=directory recurse=yes

- name: install {{ software.redis.version }}
  command: make install chdir=/tmp/redis-{{ software.redis.version }}
  when: result.rc != 0 or result.stdout.split()[1] != software.redis.version
