---

- name: install mongodb signing key
  apt_key: keyserver=keyserver.ubuntu.com id=7F0CEB10 state=present

- name: add repository
  apt_repository: repo='deb http://repo.mongodb.org/apt/debian wheezy/mongodb-org/3.0 main'

- name: install mongodb
  apt: pkg=mongodb-org state=latest
