---

- name: install tokumx-mongodb signing key
  apt_key: keyserver=keyserver.ubuntu.com id=505A7412 state=present

- name: add repository
  apt_repository: repo='deb [arch=amd64] http://s3.amazonaws.com/tokumx-debs wheezy main'

- name: install tokumx-mongodb
  apt: pkg=tokumx state=latest
