---

- name: download
  get_url: url={{ download.geoip.url }} dest=/tmp/{{ download.geoip.url | basename }}

- name: extract
  unarchive: src=/tmp/{{ download.geoip.url | basename }} dest=/tmp copy=no

- name: configure
  command: ./configure --prefix=/usr/local/geoip chdir=/tmp/GeoIP-{{ software.geoip.version }}

- name: make
  command: make -j{{ ansible_processor_cores }} chdir=/tmp/GeoIP-{{ software.geoip.version }}

- name: make install {{ software.geoip.version }}
  command: make install chdir=/tmp/GeoIP-{{ software.geoip.version }}

- name: clean up
  command: rm -rf {{ item}}
  with_items:
    - /tmp/{{ download.geoip.url | basename }}
    - /tmp/GeoIP-{{ software.geoip.version }}
