---

- name: get current version
  command: /usr/local/bin/node -v
  register: result
  ignore_errors: True
  changed_when: False

- name: install dependencies and packages
  apt: pkg={{ item }} state=installed
  with_items:
    - ruby-compass
    - ruby-sass
  when: result.rc != 0 or result.stdout.lstrip('v') != software.nodejs.version

- name: download
  get_url: url={{ download.nodejs.url }} dest=/tmp/{{ download.nodejs.url | basename }}
  when: result.rc != 0 or result.stdout.lstrip('v') != software.nodejs.version

- name: extract
  unarchive: src=/tmp/{{ download.nodejs.url | basename }} dest=/tmp copy=no
  when: result.rc != 0 or result.stdout.lstrip('v') != software.nodejs.version

- name: configure
  command: ./configure chdir=/tmp/node-v{{ software.nodejs.version }}
  when: result.rc != 0 or result.stdout.lstrip('v') != software.nodejs.version

- name: make
  command: make chdir=/tmp/node-v{{ software.nodejs.version }}
  when: result.rc != 0 or result.stdout.lstrip('v') != software.nodejs.version

- name: make install {{ software.nodejs.version }}
  command: make install chdir=/tmp/node-v{{ software.nodejs.version }}
  when: result.rc != 0 or result.stdout.lstrip('v') != software.nodejs.version
