---

- name: get current kafka version
  shell: test -f /usr/local/kafka/libs/kafka_{{ software.kafka.scala }}-{{ software.kafka.version }}.jar && echo 0 || echo 1
  register: result
  ignore_errors: True
  changed_when: False

- name: install dependencies and packages
  apt: pkg={{ item }} state=installed
  with_items:
    - libhawtjni-runtime-java
    - libjansi-native-java
    - libjansi-java
    - libssl-dev
    - libsasl2-dev
  when: result.stdout != "0"

- name: clean up
  command: rm -rf {{ item}}
  with_items:
    - /tmp/{{ download.scala.url | basename }}
    - /tmp/{{ download.kafka.url | basename }}
    - /tmp/librdkafka
  when: result.stdout != "0"

- name: librdkafka | clone
  git: repo={{ download.kafka.dep.librdkafka }} dest=/tmp/librdkafka
  when: result.stdout != "0"

- name: librdkafka | configure
  command: ./configure chdir=/tmp/librdkafka
  when: result.stdout != "0"

- name: librdkafka | make
  command: make -j{{ ansible_processor_cores }} chdir=/tmp/librdkafka
  when: result.stdout != "0"

- name: librdkafka | make install
  command: make install chdir=/tmp/librdkafka
  when: result.stdout != "0"
  notify:
    - run ldconfig

- name: scala-lang | download
  get_url: url={{ download.scala.url }} dest=/tmp/{{ download.scala.url | basename }}
  when: result.stdout != "0"

- name: scala-lang | install
  apt: deb=/tmp/{{ download.scala.url | basename }}
  when: result.stdout != "0"

- name: download
  get_url: url={{ download.kafka.url }} dest=/tmp/{{ download.kafka.url | basename }}
  when: result.stdout != "0"

- name: extract
  unarchive: src=/tmp/{{ download.kafka.url | basename }} dest=/tmp copy=no
  when: result.stdout != "0"

- name: replace binaries
  shell: if [ -d /tmp/kafka_{{ software.kafka.scala }}-{{ software.kafka.version}} ]; then rm -rf /usr/local/kafka; mv /tmp/kafka_{{ software.kafka.scala }}-{{ software.kafka.version}} /usr/local/kafka; fi
  when: result.stdout != "0"

- name: clean up
  command: rm -rf {{ item}}
  with_items:
    - /tmp/{{ download.scala.url | basename }}
    - /tmp/{{ download.kafka.url | basename }}
    - /tmp/librdkafka
  when: result.stdout != "0"
