---

- name: get current version
  command: /opt/mozjpeg/bin/cjpeg -version
  register: result
  ignore_errors: True
  changed_when: False

- name: install dependencies and packages
  apt: pkg={{ item }} state=installed
  with_items:
    - autoconf
    - automake
    - libtool
    - nasm
    - pkg-config
  when: result.rc != 0 or result.stderr.split()[2] != software.mozjpeg.version

- name: download
  get_url: url={{ download.mozjpeg.url }} dest=/tmp/{{ download.mozjpeg.url | basename }}
  when: result.rc != 0 or result.stderr.split()[2] != software.mozjpeg.version

- name: extract
  unarchive: src=/tmp/{{ download.mozjpeg.url | basename }} dest=/tmp copy=no
  when: result.rc != 0 or result.stderr.split()[2] != software.mozjpeg.version

- name: configure
  command: ./configure chdir=/tmp/mozjpeg-{{ software.mozjpeg.version }}
  when: result.rc != 0 or result.stderr.split()[2] != software.mozjpeg.version

- name: make
  command: make -j{{ ansible_processor_cores }} chdir=/tmp/mozjpeg-{{ software.mozjpeg.version }}
  when: result.rc != 0 or result.stderr.split()[2] != software.mozjpeg.version

- name: make install
  command: make install chdir=/tmp/mozjpeg-{{ software.mozjpeg.version }}
  when: result.rc != 0 or result.stderr.split()[2] != software.mozjpeg.version
  notify:
    - run ldconfig
