---

- name: get current version
  command: /opt/mozjpeg/bin/cjpeg -version
  register: result
  ignore_errors: True
  changed_when: False

- name: install dependencies and packages
  apt: pkg={{ item }} state=installed
  with_items:
    - nasm
  when: result.rc != 0 or result.stdout.split()[2] != software.mozjpeg.version

- name: clone
  git: repo={{ download.mozjpeg.url }} dest=/tmp/mozjpeg
  when: result.rc != 0 or result.stdout.split()[2] != software.mozjpeg.version

- name: autoreconf
  command: autoreconf -fiv chdir=/tmp/mozjpeg
  when: result.rc != 0 or result.stdout.split()[2] != software.mozjpeg.version

- name: configure
  command: ./configure chdir=/tmp/mozjpeg
  when: result.rc != 0 or result.stdout.split()[2] != software.mozjpeg.version

- name: make
  command: make -j{{ ansible_processor_cores }} chdir=/tmp/mozjpeg
  when: result.rc != 0 or result.stdout.split()[2] != software.mozjpeg.version

- name: make install
  command: make install chdir=/tmp/mozjpeg
  when: result.rc != 0 or result.stdout.split()[2] != software.mozjpeg.version
