---

- name: install dependencies and packages
  apt: pkg={{ item }} state=installed
  with_items:
    - libaio-dev
    - python-software-properties

- name: add mariadb pgp key
  apt_key: keyserver=keyserver.ubuntu.com id=0xcbcb082a1bb943db

- name: add repository
  apt_repository: repo='deb http://ftp.osuosl.org/pub/mariadb/repo/10.0/debian jessie main' state=present

- name: install mariadb
  apt: pkg={{ item }} state=latest update_cache=yes
  with_items:
    - mariadb-server
    - libmariadbclient-dev
