---

- name: get current version
  command: /usr/local/bin/node -v
  register: result
  ignore_errors: True
  changed_when: False

- name: install dependencies and packages
  apt: pkg={{ item }} state=installed
  with_items:
    - ruby-compass
    - ruby-sass
  when: result.rc != 0 or result.stdout.lstrip('v') != software.iojs.version

- name: download
  get_url: url={{ download.iojs.url }} dest=/tmp/{{ download.iojs.url | basename }}
  when: result.rc != 0 or result.stdout.lstrip('v') != software.iojs.version

- name: extract
  unarchive: src=/tmp/{{ download.iojs.url | basename }} dest=/tmp copy=no
  when: result.rc != 0 or result.stdout.lstrip('v') != software.iojs.version

- name: configure
  command: ./configure chdir=/tmp/iojs-v{{ software.iojs.version }}
  when: result.rc != 0 or result.stdout.lstrip('v') != software.iojs.version

- name: make
  command: make -j{{ ansible_processor_cores }} chdir=/tmp/iojs-v{{ software.iojs.version }}
  when: result.rc != 0 or result.stdout.lstrip('v') != software.iojs.version

- name: make install {{ software.iojs.version }}
  command: make install chdir=/tmp/iojs-v{{ software.iojs.version }}
  when: result.rc != 0 or result.stdout.lstrip('v') != software.iojs.version

- name: clean up
  command: rm -rf {{ item}}
  with_items:
    - /tmp/{{ download.iojs.url | basename }}
    - /tmp/iojs-v{{ software.iojs.version }}
  when: result.rc != 0 or result.stdout.lstrip('v') != software.iojs.version
