---

- name: get current version
  command: /usr/sbin/named -v
  register: result
  ignore_errors: True
  changed_when: False

- name: install dependencies and packages
  apt: pkg={{ item }} state=installed
  with_items:
    - libkrb5-dev
  when: result.rc != 0 or result.stdout.split()[1] != '{{ software.bind.version.lstrip("bind-") }}-geoip-1.3'

- name: download
  get_url: url={{ download.bind.url }} dest=/tmp/{{ software.bind.version }}.tar.gz
  when: result.rc != 0 or result.stdout.split()[1] != '{{ software.bind.version.lstrip("bind-") }}-geoip-1.3'

- name: clean directory
  command: rm -rf /tmp/{{ software.bind.version }}
  when: result.rc != 0 or result.stdout.split()[1] != '{{ software.bind.version.lstrip("bind-") }}-geoip-1.3'

- name: extract
  unarchive: src=/tmp/{{ software.bind.version }}.tar.gz dest=/tmp copy=no
  when: result.rc != 0 or result.stdout.split()[1] != '{{ software.bind.version.lstrip("bind-") }}-geoip-1.3'

- name: copy patch
  copy: src=../files/geoip.patch dest=/tmp/{{ software.bind.version }}/geoip.patch
  when: result.rc != 0 or result.stdout.split()[1] != '{{ software.bind.version.lstrip("bind-") }}-geoip-1.3'

- name: apply patch
  shell: patch -p1 < geoip.patch chdir=/tmp/{{ software.bind.version }}
  when: result.rc != 0 or result.stdout.split()[1] != '{{ software.bind.version.lstrip("bind-") }}-geoip-1.3'

- name: autoconf
  command: autoconf chdir=/tmp/{{ software.bind.version }}
  when: result.rc != 0 or result.stdout.split()[1] != '{{ software.bind.version.lstrip("bind-") }}-geoip-1.3'

- name: configure
  command: ./configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --sysconfdir=/etc/bind --localstatedir=/var --enable-threads --enable-largefile --with-libtool --enable-shared --enable-static --with-openssl=/usr --with-gssapi=/usr --with-gnu-ld --with-dlz-postgres=no --with-dlz-mysql=no --with-dlz-filesystem=yes --with-dlz-stub=yes --with-dlz-dlopen=yes --with-geoip=/usr/local/geoip --enable-ipv6 CFLAGS=-fno-strict-aliasing chdir=/tmp/{{ software.bind.version }}
  when: result.rc != 0 or result.stdout.split()[1] != '{{ software.bind.version.lstrip("bind-") }}-geoip-1.3'

- name: make
  command: make chdir=/tmp/{{ software.bind.version }}
  when: result.rc != 0 or result.stdout.split()[1] != '{{ software.bind.version.lstrip("bind-") }}-geoip-1.3'

- name: make install {{ software.bind.version }}
  command: make install chdir=/tmp/{{ software.bind.version }}
  when: result.rc != 0 or result.stdout.split()[1] != '{{ software.bind.version.lstrip("bind-") }}-geoip-1.3'
